local map = vim.keymap.set
local telescope = require("telescope.builtin")
local themes = require("telescope.themes")

local function opts(desc)
	return { desc = desc, silent = true }
end

map("n", "<C-p>", telescope.commands, opts("Command palette"))
map("n", "<C-f>", function()
	vim.lsp.buf.format({ async = true })
end, opts("Format buffer"))
map("n", "<C-n>", "<cmd>Neotree position=right focus<CR>", opts("Focus Neo-tree"))
map("n", "<leader>rl", function()
	vim.cmd("luafile %")
	vim.notify("Reloaded " .. vim.api.nvim_buf_get_name(0))
end, opts("Reload current Lua config"))

map("n", "<Tab>", "<cmd>BufferLineCycleNext<CR>", opts("Go to next buffer"))
map("n", "<S-Tab>", "<cmd>BufferLineCyclePrev<CR>", opts("Go to previous buffer"))
map("n", "<A-h>", "<cmd>BufferLineMovePrev<CR>", opts("Move buffer left"))
map("n", "<A-l>", "<cmd>BufferLineMoveNext<CR>", opts("Move buffer right"))
map("n", "<A-H>", "<cmd>BufferLineCloseLeft<CR>", opts("Close buffers to the left"))
map("n", "<A-L>", "<cmd>BufferLineCloseRight<CR>", opts("Close buffers to the right"))

map("n", "<leader>tP", require("util.profile").toggle_profile, opts("Toggle plugin profiling"))
map("n", "<leader>pp", function()
	telescope.find_files(themes.get_dropdown({}))
end, opts("Find files in workspace"))
map("n", "<leader>pg", telescope.grep_string, opts("Grep word under cursor"))
map("n", "<leader>pb", function()
	telescope.buffers(themes.get_dropdown({}))
end, opts("Find buffers"))
map("n", "<leader>pk", telescope.keymaps, opts("Find keymap"))
map("n", "<leader>pt", telescope.lsp_dynamic_workspace_symbols, opts("Find LSP workspace symbol"))
map("n", "<leader>ph", function()
	telescope.lsp_references({ initial_mode = "normal" })
end, opts("Find LSP references"))
map("n", "<leader>pi", function()
	telescope.lsp_implementations({ initial_mode = "normal" })
end, opts("Find LSP implementations"))
map({ "n", "x" }, "<leader>ps", "<cmd>GrugFar<CR>", opts("Workspace find and replace"))

map("n", "<A-j>", "<cmd>move .+1<CR>==", opts("Move current line down"))
map("n", "<A-k>", "<cmd>move .-2<CR>==", opts("Move current line up"))
map("i", "<A-j>", "<Esc><cmd>move .+1<CR>==gi", opts("Move current line down"))
map("i", "<A-k>", "<Esc><cmd>move .-2<CR>==gi", opts("Move current line up"))
map("x", "<A-j>", "<cmd>move '>+1<CR>gv=gv", opts("Move selected text down"))
map("x", "<A-k>", "<cmd>move '<-2<CR>gv=gv", opts("Move selected text up"))

map("n", "<C-h>", "<C-w>h", opts("Move to left window"))
map("n", "<C-j>", "<C-w>j", opts("Move to lower window"))
map("n", "<C-k>", "<C-w>k", opts("Move to upper window"))
map("n", "<C-l>", "<C-w>l", opts("Move to right window"))
map("n", "<C-Tab>", "<cmd>tabnext<CR>", opts("Go to next tab"))
map("n", "<C-S-Tab>", "<cmd>tabprevious<CR>", opts("Go to previous tab"))

map({ "n", "x" }, "<leader>ca", "<cmd>Lspsaga code_action<CR>", opts("Show code actions"))
map("n", "<leader>s", "<cmd>Lspsaga hover_doc<CR>", opts("Show LSP hover documentation"))
map("n", "gh", "<cmd>Lspsaga lsp_finder<CR>", opts("Find LSP references"))
map("n", "K", "<cmd>Lspsaga hover_doc<CR>", opts("Show hover documentation"))
map("n", "gs", "<cmd>Lspsaga signature_help<CR>", opts("Show signature help"))
map("n", "gr", "<cmd>Lspsaga rename<CR>", opts("Rename symbol"))
map("n", "<F2>", "<cmd>Lspsaga rename<CR>", opts("Rename symbol"))
map("n", "gd", vim.lsp.buf.definition, opts("Go to definition"))
map("n", "<leader>cd", "<cmd>Lspsaga show_line_diagnostics<CR>", opts("Show line diagnostics"))
map("n", "<A-n>", "<cmd>Lspsaga diagnostic_jump_next<CR>", opts("Go to next diagnostic"))
map("n", "<A-N>", "<cmd>Lspsaga diagnostic_jump_prev<CR>", opts("Go to previous diagnostic"))
map("n", "<leader>tf", "<cmd>Neotree toggle position=right<CR>", opts("Toggle file explorer"))
